name: test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, edited]

env:
  FOUNDRY_PROFILE: ci
  NODE_VERSION: 16.17.0

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install
        run: npm ci --include=dev
      - name: Solhint check
        run: npx solhint '{contracts,test,scripts}/**/*.sol'
      - name: Prettier check
        run: npx prettier --check .

  forge-check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    env:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
